// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AllGraphController from "./all_graph_controller"
application.register("all-graph", AllGraphController)

import GraphController from "./graph_controller"
application.register("graph", GraphController)

import ButtonController from "./button_controller"
application.register("button", ButtonController)
